steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops','.']
images:
- 'gcr.io/$PROJECT_ID/gcpdevops'

steps:
  #build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
  #push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
  #deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=europe-central2
  - --cluster=gcp-learning-autopilot-cluster-1
  - --namespace=gcp-devops-prod
